### ISSUE TITLE
Training for setting up automatic tests of a github repository

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/resources#23] opened 2020-10-02 13:50 UTC
Ideally someone with good experience with either Travis or Jenkins could show us how it's done. Maybe @tom-andersson?

**Comment by Croydon-Brixton** [comment] 2020-10-02 14:02
@sdat2 I did some github CI (continuous integration) - if that would be helpful, I can look into that in addition to the above :) 
( But I think for most options we'd need a Github pro account as organisation)

**Comment by sdat2** [comment] 2020-10-02 14:22
Hi @Croydon-Brixton that sounds great. I guess this issue is quite similar to #3. Maybe I should merge the issues?

**Comment by Croydon-Brixton** [comment] 2020-10-02 14:48
Yes, let's merge them

**Comment by herbiebradley** [comment] 2020-10-02 15:50
IIRC the standard way to merge issues is to put a comment that the issue is a duplicate of another issue, which creates an automatic link, then the issue can be closed:

**Comment by herbiebradley** [comment] 2020-10-02 15:51
Duplicate of #3

**Closed as completed** 2020-10-02 18:31 UTC
